# Generated by Django 4.2 on 2023-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
