# Generated by Django 4.2 on 2023-08-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_vote_is_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='voted',
            field=models.IntegerField(default=0),
        ),
    ]
