# Generated by Django 4.2 on 2023-08-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_candidate_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_voted',
        ),
        migrations.AddField(
            model_name='voter',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
